apiVersion: v1
description: Benji Backup for Kubernetes
name: benji-k8s
version: 1.0.0
maintainers:
  - name: Elemental
    email: lf@elemental.net
dependencies:
  - name: postgresql
    version: ~11.1.17
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: prometheus-pushgateway
    alias: pushgateway
    version: ~1.16.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: pushgateway.enabled
