---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ tuple . "" | include "benji.fullname" }}
  labels:
{{ include "benji.labels" $ | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ tuple . "" | include "benji.fullname" }}
subjects:
  - kind: ServiceAccount
    name: {{ tuple . "" | include "benji.fullname" }}
    namespace: {{ .Release.Namespace }}
