{{- if .Values.fsfreeze.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ tuple . "fsfreeze" | include "benji.fullname" }}
  labels:
      app.kubernetes.io/name: {{ include "benji.name" . }}
      helm.sh/chart: {{ include "benji.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: fsfreeze
      app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "benji.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: fsfreeze
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "benji.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: fsfreeze
        # This is used to find fsfreeze pods
        benji-backup.me/component: "fsfreeze"
    spec:
      serviceAccountName: {{ tuple . "" | include "benji.fullname" }}
      dnsPolicy: ClusterFirstWithHostNet
{{- if .Values.fsfreeze.priorityClassName }}
      priorityClassName: {{ .Values.fsfreeze.priorityClassName }}
{{- end }}
      containers:
        - name: fsfreeze
          image: "{{ .Values.fsfreeze.image.registry }}/{{ .Values.fsfreeze.image.repository }}:{{ .Values.fsfreeze.image.tag }}"
          imagePullPolicy: {{ .Values.fsfreeze.image.pullPolicy }}
          securityContext:
            privileged: true
          command:
            - sleep
            - 365d
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
{{- if .Values.benji.volumeMounts }}
            {{ toYaml .Values.fsfreeze.volumeMounts | nindent 12 }}
{{- end }}
          resources:
            {{ toYaml .Values.fsfreeze.resources | nindent 12 }}
      hostNetwork: false
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/{{ .Values.timeZone }}
{{- if .Values.benji.volumes }}
        {{ toYaml .Values.fsfreeze.volumes | nindent 8 }}
{{- end }}
{{- with .Values.fsfreeze.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.fsfreeze.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.fsfreeze.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
{{- end }}
{{- end }}
