{{- if .Values.benji.configurationFromSecrets.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.benji.configurationFromSecrets.secretsName }}
  labels:
{{ include "benji.labels" . | indent 4 }}
type: Opaque
data: 
  benji.yaml: |
{{ .Values.benji.configurationFromSecrets.configuration | toYaml | nindent 4 }
{{- end }}
{{- if .Values.ceph.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ceph.key }}
  labels:
{{ include "benji.labels" . | indent 4 }}
type: Opaque
data:
  keyring: |
{{ include "benji.ceph-keyring" . | b64enc | indent 4 }}
{{- end }}
