{{- if .Values.ceph.createKeyringSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ceph.key }}
  labels:
    app.kubernetes.io/name: {{ include "benji.name" . }}
    helm.sh/chart: {{ include "benji.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: benji
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  keyring: |
{{ include "benji.ceph-keyring" . | b64enc | indent 4 }}
{{- end }}
