{{- if .Values.ceph.createKeyringSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ceph.key }}
  labels:
{{ include "benji.labels" . | indent 4 }}
type: Opaque
data:
  keyring: |
{{ include "benji.ceph-keyring" . | b64enc | indent 4 }}
{{- end }}
